import os
import json
from fastapi import FastAPI, HTTPException, status, Depends
from pydantic import BaseModel, Field
from typing import Optional
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, Response
from fastapi.staticfiles import StaticFiles
from sqlalchemy.orm import Session
from backend.app.services.rag_engine import run_clinical_rag
from backend.app.services.pdf_export import generate_report_pdf
from backend.app.routes import clinical_chat, auth_routes
from backend.app.database import Base, engine, get_db
from backend.app import models
from backend.app.auth import get_current_doctor

app = FastAPI(
    title="Clinical Decision Support System (CDSS) Engine",
    description="Production-grade local RAG engine for clinical guideline retrieval and reporting.",
    version="1.0.0"
)

# Creates all tables (patients, reports, chat_history, documents,
# doctor_accounts) on startup if they don't already exist. Safe to run
# every time - it never touches tables/rows that already exist.
Base.metadata.create_all(bind=engine)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth_routes.router)
app.include_router(clinical_chat.router)


class VitalsModel(BaseModel):
    blood_pressure: str = Field(..., example="120/80 mmHg")
    pulse_rate: int = Field(..., example=72)
    temperature: float = Field(..., example=98.6)
    oxygen_saturation: int = Field(..., example=98)

class PatientAnalysisRequest(BaseModel):
    patient_name: str
    age: int
    gender: str
    medical_history: Optional[str] = None
    current_symptoms: str
    vitals: VitalsModel
    lab_results: Optional[str] = None
    imaging_findings: Optional[str] = None
    doctor_notes: Optional[str] = None


@app.post("/api/v1/clinical/generate-report")
async def generate_patient_report(
    payload: PatientAnalysisRequest,
    db: Session = Depends(get_db),
    current_doctor: models.DoctorAccount = Depends(get_current_doctor),
):
    try:
        patient_data = payload.model_dump()
        report_output = run_clinical_rag(patient_data)

        # --- Phase 3: persist the patient + report to the database ---
        # Look up an existing patient by name first so re-running a
        # report for the same patient doesn't create duplicate rows.
        patient = db.query(models.Patient).filter(
            models.Patient.full_name == payload.patient_name
        ).first()
        if patient is None:
            patient = models.Patient(
                full_name=payload.patient_name,
                age=payload.age,
                gender=payload.gender,
            )
            db.add(patient)
            db.commit()
            db.refresh(patient)

        db_report = models.Report(
            patient_id=patient.id,
            doctor_id=current_doctor.id,  # Phase 4: now tied to the logged-in doctor
            current_symptoms=payload.current_symptoms,
            vitals_json=json.dumps(payload.vitals.model_dump()),
            medical_history=payload.medical_history,
            lab_results=payload.lab_results,
            imaging_findings=payload.imaging_findings,
            doctor_notes=payload.doctor_notes,
            report_text=str(report_output),
        )
        db.add(db_report)
        db.commit()
        db.refresh(db_report)
        # --- end persistence ---

        filename = f"Clinical_Report_{payload.patient_name.replace(' ', '_')}.txt"
        file_path = os.path.join(os.getcwd(), filename)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(f"CLINICAL DECISION SUPPORT SYSTEM REPORT\n")
            f.write(f"=========================================\n")
            f.write(f"Patient Name: {payload.patient_name}\n")
            f.write(f"Age: {payload.age} | Gender: {payload.gender}\n")
            f.write(f"Report ID: {db_report.id} (saved to database)\n")
            f.write(f"Generated by: Dr. {current_doctor.full_name}\n")
            f.write(f"-----------------------------------------\n\n")
            f.write(str(report_output))

        return FileResponse(
            path=file_path,
            filename=filename,
            media_type="text/plain"
        )

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Fault inside internal processing pipeline: {str(e)}"
        )


@app.get("/api/v1/clinical/reports")
def list_reports(
    db: Session = Depends(get_db),
    current_doctor: models.DoctorAccount = Depends(get_current_doctor),
):
    """Phase 3 addition: view every report ever generated, proving
    persistence actually works (not just a claim). Phase 4: now requires
    login, since these contain patient data."""
    reports = db.query(models.Report).order_by(models.Report.created_at.desc()).all()
    return [
        {
            "id": r.id,
            "patient_name": r.patient.full_name if r.patient else None,
            "created_at": r.created_at,
            "report_preview": r.report_text[:200],
        }
        for r in reports
    ]


@app.get("/api/v1/clinical/reports/{report_id}")
def get_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_doctor: models.DoctorAccount = Depends(get_current_doctor),
):
    report = db.query(models.Report).filter(models.Report.id == report_id).first()
    if report is None:
        raise HTTPException(status_code=404, detail="Report not found")
    return {
        "id": report.id,
        "patient_name": report.patient.full_name if report.patient else None,
        "created_at": report.created_at,
        "report_text": report.report_text,
    }


@app.get("/api/v1/clinical/reports/{report_id}/pdf")
def get_report_pdf(
    report_id: int,
    db: Session = Depends(get_db),
    current_doctor: models.DoctorAccount = Depends(get_current_doctor),
):
    """Phase 6: renders an already-generated report as a formatted PDF.
    Reuses the saved report_text - no LLM call, so this is fast even
    though the original report generation wasn't."""
    report = db.query(models.Report).filter(models.Report.id == report_id).first()
    if report is None:
        raise HTTPException(status_code=404, detail="Report not found")

    doctor_who_generated = report.doctor.full_name if report.doctor else current_doctor.full_name

    pdf_bytes = generate_report_pdf(
        report_id=report.id,
        patient_name=report.patient.full_name if report.patient else "Unknown Patient",
        patient_age=report.patient.age if report.patient else "N/A",
        patient_gender=report.patient.gender if report.patient else "N/A",
        doctor_name=doctor_who_generated,
        created_at=report.created_at,
        report_text=report.report_text,
    )

    filename = f"Clinical_Report_{(report.patient.full_name if report.patient else 'Patient').replace(' ', '_')}_{report.id}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@app.post("/api/recommend")
async def legacy_recommendation(
    payload: clinical_chat.ChatRequest,
    db: Session = Depends(get_db),
    current_doctor: models.DoctorAccount = Depends(get_current_doctor),
):
    """Compatibility route for the original index.html prototype."""
    response = await clinical_chat.clinical_chat(payload, db, current_doctor)
    return {"recommendation": response.answer, "sources": response.sources}


# Serves the AccuCare landing page (static/index.html) at "/", and any
# other files under static/ (e.g. static/images/...) at their matching
# path. Must be registered AFTER every @app.get/@app.post route above -
# mounting it earlier would let it shadow the API routes instead of the
# other way around. The old root route (`@app.get("/") -> {"status": ...}`)
# has been removed - it was intercepting "/" before this mount ever got
# a chance to serve the actual landing page.
app.mount("/", StaticFiles(directory="static", html=True), name="static")


@app.get("/health")
def health_check():
    return {"status": "healthy", "service": "Modular API Engine active"}